scrape_configs:
- job_name: 'prometheus'
  scrape_interval: 1m
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'node'
  scrape_interval: 1m
  static_configs:
  - targets: ['host-node-exporter:9100']

- job_name: 'postgres'
  scrape_interval: 1m
  static_configs:
    - targets: ['host-postgres-exporter:9187']

- job_name: 'rabbitmq'
  scrape_interval: 1m
  static_configs:
    - targets: ['some-rabbit:15692']

- job_name: 'blackbox'
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
    - targets:
      - https://www.google.com
      - https://www.youtube.com
      - https://login.cybersoft.edu.vn/
      - https://cybersoft.edu.vn/
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: host-blackbox-exporter:9115

- job_name: 'blackbox_exporter'
  static_configs:
  - targets: [host-blackbox-exporter:9115]