FROM nginx

WORKDIR /usr/share/nginx/html

# Dấu chấm đầu tiên: toàn bộ file trong thư mục
# Dấu chấm thứ hai: vị trí file code được copy trong máy ảo

COPY . .

# Tạo image: docker build . -t tên_image
